### PR TITLE
OP-698: remove resolution

### PR DESCRIPTION
**Pull request by geektortoise**

### CODE REVIEW

**Comment by geektortoise** [comment]
@loic911 
Ok except for 

- grails-app/services/be/cytomine/image/AbstractImageService.groovy. Too much logs (log.info("10"), log.info("Image=$images" ) )  
- grails-app/services/be/cytomine/utils/DataTablesService.groovy  resolution is deleted but there is no physicalSize equivalent. Instead of deleting the resolution, change it for PhysicalSizeX

**Comment by loic911** [comment]
Is datatables (DataTablesService) still useful? I can't see any usage of _datatables_ parameter ?

**Comment by geektortoise** [comment]
I see one call here 
https://github.com/cytomine/Cytomine-core/blob/ef7b08102b6bf3682197400f80488c98b30068f0/grails-app/controllers/be/cytomine/api/image/RestImageInstanceController.groovy#L121

**Comment by loic911** [comment]
Yep, but I mean is the params.datatables still useful ? ;-) I can't see any usage of datatables parameter in the frontend nor in the js client.
I think it's a legacy from the previous jquery frontend and the datatables dependency (https://datatables.net/)

**Comment by geektortoise** [comment]
Thanks

**Comment by geektortoise** [comment]
I will set a @Deprecated for Datatable service

**Pull request merged**
